# Generated by Django 4.2.23 on 2025-06-24 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True, verbose_name='Город')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адрес')),
                ('avg_salary', models.FloatField(verbose_name='Средняя зарплата (руб)')),
                ('vacancy_share', models.FloatField(verbose_name='Доля вакансий (%)')),
                ('avg_salary_android', models.FloatField(blank=True, null=True, verbose_name='Средняя зарплата Android (руб)')),
                ('vacancy_share_android', models.FloatField(blank=True, null=True, verbose_name='Доля вакансий Android (%)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статистика по городам',
                'verbose_name_plural': 'Статистика по городам',
                'ordering': ('-avg_salary',),
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Описание профессии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='YearStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Год')),
                ('avg_salary', models.FloatField(verbose_name='Средняя зарплата (руб)')),
                ('vacancy_count', models.IntegerField(verbose_name='Количество вакансий')),
                ('avg_salary_android', models.FloatField(blank=True, null=True, verbose_name='Средняя зарплата Android (руб)')),
                ('vacancy_count_android', models.IntegerField(blank=True, null=True, verbose_name='Количество вакансий Android')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статистика по годам',
                'verbose_name_plural': 'Статистика по годам',
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название вакансии')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('company', models.CharField(max_length=150, verbose_name='Компания')),
                ('salary', models.CharField(max_length=100, verbose_name='Оклад')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('source_id', models.CharField(max_length=20, unique=True, verbose_name='ID вакансии на HH')),
                ('is_android', models.BooleanField(default=True, verbose_name='Для Android-разработчика')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ('-published_at',),
                'indexes': [models.Index(fields=['-published_at'], name='main_vacanc_publish_05e8dd_idx'), models.Index(fields=['is_android'], name='main_vacanc_is_andr_cfab15_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название навыка')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адрес')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('count', models.IntegerField(verbose_name='Количество упоминаний')),
                ('is_android', models.BooleanField(default=False, verbose_name='Для Android-разработчика')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ('-year', '-count'),
                'unique_together': {('name', 'year', 'is_android')},
            },
        ),
        migrations.CreateModel(
            name='ProfessionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profession_images/%Y/%m/%d', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание изображения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Изображение профессии',
                'verbose_name_plural': 'Изображения профессии',
                'ordering': ('-created',),
            },
        ),
    ]
